export const platforms = [
    "PC",
    "PlayStation 5",
    "PlayStation 4",
    "PlayStation 3",
    "PlayStation 2",
    "PlayStation 1",
    "PS Vita",
    "PSP",
    "Apple Macintosh",
    "Classic Macintosh",
    "Apple II",
    "macOS",
    "iOS",
    "Xbox One",
    "Xbox Series S/X",
    "Xbox 360",
    "Nintendo Switch",
    "Nintendo 3DS",
    "Nintendo DS",
    "Nintendo DSi",
    "Nintendo 64",
    "Nintendo 64",
    "GameCube",
    "Game Boy Advance",
    "Game Boy Color",
    "Game Boy",
    "SNES",
    "NES",
    "Atari",
    "Atari 7800",
    "Atari 5200",
    "Atari 2600",
    "Atari Flashback",
    "Atari 8-bit",
    "Atari ST",
    "Atari Lynx",
    "Atari XEGS",
    "Jaguar",
    "Genesis",
    "Commodore / Amiga",
    "SEGA",
    "SEGA Saturn",
    "SEGA CD",
    "SEGA 32X",
    "SEGA Master System",
    "Dreamcast",
    "Game Gear",
    "3DO",
    "Neo Geo",
    "Web",
    "Wii U",
    "Wii",
    "GameCube",
    "Android",
    "Linux"
  ];

